version: '2'
services:
  redis:
    image: redis:7-alpine
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data

  app:
    build: ./
    ports:
      - 9292:9292
    environment:
      PORT: 9292
      REDIS_URL: redis://redis:6379/0
    depends_on:
      - redis

volumes:
  redis_data:
